### ISSUE TITLE
Problem installing 

### ISSUE THREAD

**Issue by Alvaro8gb** [explosion/spacy-huggingface-hub#22]
I have upload a model to HF hub, but I can not installed with

`
!pip install https://huggingface.co/Alvaro8gb/es_BreastCancerNER/resolve/main/es_BreastCancerNER-any-py3-none-any.whl
`

An error appears:

`ERROR: Invalid requirement: 'es-BreastCancerNER==any': Expected end or semicolon (after name and no valid version specifier)
    es-BreastCancerNER==any`

**Comment by JeswinMS4** [comment]
I had uploaded my NER model trained through Spacy on huggingface. While trying to inference, I am facing this issue:

    pip install https://huggingface.co/JeswinMS4/en_resume_pipeline/resolve/main/en_resume_pipeline-any-py3-none-any.whl


> ERROR: Invalid requirement: 'en-resume-pipeline==any': Expected end or
> semicolon (after name and no valid version specifier)
>     en-resume-pipeline==any
>                       ^


The documentation also states this way to load. Even I was facing the same issue. Any fix possible??

**Comment by Wauplin** [comment]
Hey there, I just tried running 

```
pip install https://huggingface.co/JeswinMS4/en_resume_pipeline/resolve/main/en_resume_pipeline-any-py3-none-any.whl
```

and it successfully installed the wheel package for me.

![image](https://github.com/user-attachments/assets/092c9e9f-28a5-49ce-b68f-1858a0e1e832)

```
(...)
Successfully installed blis-0.7.11 catalogue-2.0.10 cloudpathlib-0.18.1 confection-0.1.5 cymem-2.0.8 en-resume-pipeline-0.0.0 langcodes-3.4.0 language-data-1.2.0 marisa-trie-1.2.0 murmurhash-1.0.10 preshed-3.0.9 smart-open-7.0.4 spacy-3.7.5 spacy-alignments-0.9.1 spacy-legacy-3.0.12 spacy-loggers-1.0.5 spacy-transformers-1.3.5 srsly-2.4.8 thinc-8.2.5 wasabi-1.1.3 weasel-0.4.1 wrapt-1.16.0
```

I can't tell what's the error in your case but can it be related to an issue with pip rather than the uploaded file? (see [stackoverflow here](https://stackoverflow.com/questions/76784012/pip-install-e-fails-with-expected-end-or-semicolon-for-githttps-in-require)).

If that can help, here are the versions I have:
```
➜  ~ python --version
Python 3.10.12
➜  ~ pip --version
pip 22.0.2 from /usr/lib/python3/dist-packages/pip (python 3.10)
```

**Comment by JeswinMS4** [comment]
Yes..It was issue with the version of pip
![image](https://github.com/user-attachments/assets/231d64e3-6c0a-41b4-a72c-3b67a60b75df)
I was running 24.1.2 version of pip and this required 22.0.2. Thank you so much!!

**Comment by Alvaro8gb** [comment]
Yes is the pip version, thanks both @JeswinMS4  and @Wauplin
